name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * 1' # 毎週月曜日 3:00am
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2
        with:
          head: main
          base: main
          auto_merge: false
          auto_approve: false
