name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.9
        with:
          owner: WorldDownTown
          repo: SFSymbol
          token: ${{ secrets.GITHUB_TOKEN }}
          head: main
          base: main
          merge_method: rebase
